application: ogori-masu
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /test.*
  script: gaeunit.py

- url: .*
  script: ogori.py
